name: Events-K CI

on:
  push:
    tags-ignore:
      - '*.*.*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches:
      - 'main'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: 1.0.0
        with:
          tag_name: 1.0.0
          release_name: Release 1.0.0
          draft: false
          prerelease: false
      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          RELEASE_VERSION: 1.0.0
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Escape Camp test report
          path: build/test-results/**/*.xml
          reporter: java-junit